### ISSUE TITLE
Easy Fix: remove extra semicolon

### ISSUE THREAD

**Issue by dockleryxk** [Alipoodle/GPMDPMidnightAccent#4]
Hey, thanks for writing this! Anyways, there is a small syntax error [here](https://github.com/Alipoodle/GPMDPMidnightAccent/blob/master/gpmcss.css#L8). It's the semicolon before `!important`

**Comment by Rat1o** [comment]
What should it be changed to?

**Comment by Rat1o** [comment]
Never mind I looked at the post title and removed the semicolon

**Comment by Alipoodle** [comment]
Thanks for popping the notice, this isn't a major deal as it's one of the Comment sections so most people won't have this by default!

I will fix this issue in a commit I'll do that will check for anything else that needs updating.

**Comment by Alipoodle** [comment]
#6 This issue will now be fixed in the latest version.
As Google Play Music seems to be getting rolled out a little by Google for YouTube music, I might continue this project for YouTube Music.

**Comment by dockleryxk** [comment]
That would be awesome!
